import React from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Trash2, Calendar, Clock, Moon, Sun, Sparkles, Brain, Repeat } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { ScheduleEvent } from '@/hooks/useScheduleEvents';
import { RecurringEvent } from '@/hooks/useRecurringEvents';

const CATEGORY_CONFIG: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  sleep: { label: 'Sleep', color: 'hsl(260 60% 55%)', icon: <Moon className="h-3 w-3" /> },
  wake: { label: 'Wake Up', color: 'hsl(45 90% 50%)', icon: <Sun className="h-3 w-3" /> },
  task: { label: 'Task', color: 'hsl(var(--primary))', icon: <Calendar className="h-3 w-3" /> },
  wellness: { label: 'Wellness', color: 'hsl(160 60% 45%)', icon: <Sparkles className="h-3 w-3" /> },
  mindmate: { label: 'MindMate', color: 'hsl(270 70% 55%)', icon: <Brain className="h-3 w-3" /> },
  exercise: { label: 'Exercise', color: 'hsl(340 75% 55%)', icon: <Sparkles className="h-3 w-3" /> },
  meal: { label: 'Meal', color: 'hsl(25 85% 50%)', icon: <Clock className="h-3 w-3" /> },
  study: { label: 'Study/Work', color: 'hsl(200 70% 50%)', icon: <Calendar className="h-3 w-3" /> },
  birthday: { label: 'Birthday', color: 'hsl(340 75% 55%)', icon: <span className="text-xs">🎂</span> },
  anniversary: { label: 'Anniversary', color: 'hsl(350 80% 55%)', icon: <span className="text-xs">💍</span> },
};

interface EventListProps {
  events: ScheduleEvent[];
  recurringEventsForDate: RecurringEvent[];
  onToggleComplete: (id: string) => void;
  onDelete: (id: string) => void;
  onDeleteRecurring: (id: string) => void;
}

const formatTime = (time: string) => {
  const [h, m] = time.split(':');
  const hour = parseInt(h);
  return `${hour % 12 || 12}:${m} ${hour >= 12 ? 'PM' : 'AM'}`;
};

export const EventList = ({ events, recurringEventsForDate, onToggleComplete, onDelete, onDeleteRecurring }: EventListProps) => {
  const sortedEvents = [...events].sort((a, b) => a.start_time.localeCompare(b.start_time));

  // Merge recurring events that aren't already in scheduled events
  const allItems: { type: 'scheduled' | 'recurring'; event: ScheduleEvent | RecurringEvent }[] = [
    ...sortedEvents.map(e => ({ type: 'scheduled' as const, event: e })),
    ...recurringEventsForDate
      .filter(re => !sortedEvents.some(se => se.title === re.title && se.source === 'recurring'))
      .map(e => ({ type: 'recurring' as const, event: e })),
  ].sort((a, b) => {
    const aTime = 'start_time' in a.event ? a.event.start_time : '';
    const bTime = 'start_time' in b.event ? b.event.start_time : '';
    return aTime.localeCompare(bTime);
  });

  if (allItems.length === 0) {
    return (
      <div className="text-center py-10">
        <Calendar className="h-12 w-12 mx-auto mb-3 text-muted-foreground/30" />
        <p className="text-sm text-muted-foreground">No events for this day</p>
        <p className="text-xs text-muted-foreground/60 mt-1">Tap + to add one</p>
      </div>
    );
  }

  const completedCount = sortedEvents.filter(e => e.is_completed).length;
  const taskCount = sortedEvents.filter(e => !e.is_auto_generated).length;

  return (
    <>
      <ScrollArea className="max-h-[400px]">
        <div className="space-y-2">
          <AnimatePresence>
            {allItems.map((item, idx) => {
              const isRecurring = item.type === 'recurring';
              const event = item.event;
              const catConfig = CATEGORY_CONFIG[event.category] || CATEGORY_CONFIG.task;
              const isCompleted = !isRecurring && (event as ScheduleEvent).is_completed;
              const isAutoGenerated = !isRecurring && (event as ScheduleEvent).is_auto_generated;

              return (
                <motion.div
                  key={isRecurring ? `rec-${event.id}` : event.id}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 10 }}
                  transition={{ delay: idx * 0.03 }}
                  className={`flex items-center gap-3 p-3 rounded-xl border transition-all ${
                    isCompleted ? 'opacity-50 bg-muted/30' : 'bg-card hover:bg-accent/5'
                  }`}
                >
                  {/* Time */}
                  <div className="flex-shrink-0 w-14 text-center">
                    <span className="text-xs font-mono text-muted-foreground">
                      {formatTime(event.start_time)}
                    </span>
                  </div>

                  {/* Color bar */}
                  <div
                    className="w-1 h-10 rounded-full flex-shrink-0"
                    style={{ backgroundColor: event.color || catConfig.color }}
                  />

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1.5">
                      <span className={`text-sm font-medium ${isCompleted ? 'line-through' : ''}`}>
                        {event.title}
                      </span>
                      <Badge variant="outline" className="text-[9px] px-1 py-0 h-4" style={{ borderColor: catConfig.color, color: catConfig.color }}>
                        {catConfig.label}
                      </Badge>
                      {isRecurring && (
                        <Repeat className="h-3 w-3 text-muted-foreground/50" />
                      )}
                    </div>
                    {event.description && (
                      <p className="text-[11px] text-muted-foreground truncate">{event.description}</p>
                    )}
                    {event.end_time && (
                      <span className="text-[10px] text-muted-foreground">
                        Until {formatTime(event.end_time)}
                      </span>
                    )}
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-1 flex-shrink-0">
                    {!isRecurring && !isAutoGenerated && (
                      <Checkbox
                        checked={isCompleted}
                        onCheckedChange={() => onToggleComplete(event.id)}
                        className="h-4 w-4"
                      />
                    )}
                    {isRecurring ? (
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-6 w-6 text-muted-foreground hover:text-destructive"
                        onClick={() => onDeleteRecurring(event.id)}
                      >
                        <Trash2 className="h-3 w-3" />
                      </Button>
                    ) : !isAutoGenerated ? (
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-6 w-6 text-muted-foreground hover:text-destructive"
                        onClick={() => onDelete(event.id)}
                      >
                        <Trash2 className="h-3 w-3" />
                      </Button>
                    ) : null}
                  </div>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      </ScrollArea>

      {/* Summary */}
      <div className="mt-3 pt-3 border-t flex items-center justify-between text-xs text-muted-foreground">
        <span>{completedCount}/{taskCount} tasks done</span>
        <span>{allItems.length} events total</span>
      </div>
    </>
  );
};
