import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const PRIMARY = '#7c3aed';
const MUTED = '#64748b';

function header(doc: jsPDF, title: string, subtitle: string) {
  doc.setFillColor(PRIMARY);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 28, 'F');
  doc.setTextColor('#ffffff');
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 14);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(subtitle, 14, 22);
  doc.setTextColor('#000000');
}

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text('Generated by Zenith — MindMate Wellness', 14, h - 8);
    doc.text(`Page ${i} / ${pages}`, w - 14, h - 8, { align: 'right' });
  }
  doc.setTextColor('#000000');
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(PRIMARY);
  doc.text(text, 14, y);
  doc.setTextColor('#000000');
  doc.setFont('helvetica', 'normal');
  return y + 6;
}

export interface WellnessReportData {
  userName: string;
  timeframe: 'weekly' | 'monthly';
  avgMoodScore: number;
  positivePct: number;
  lowPct: number;
  totalMoodEntries: number;
  uniqueActiveDays: number;
  periodDays: number;
  journalCount: number;
  mindMateUsage: number;
  totalDaysUsed: number;
  mostCommonMood: string | null;
  moodCounts: Record<string, number>;
  recentMoods: Array<{ date: string; mood: string; reason: string }>;
  recentJournals: Array<{ date: string; preview: string }>;
  aiTip?: string;
}

export function generateWellnessReport(data: WellnessReportData) {
  const doc = new jsPDF();
  const period = data.timeframe === 'weekly' ? 'Weekly' : 'Monthly';
  header(doc, 'Wellness Report', `${period} • ${data.userName} • ${new Date().toLocaleDateString()}`);

  let y = 38;
  y = sectionTitle(doc, 'Summary', y);
  autoTable(doc, {
    startY: y,
    theme: 'grid',
    headStyles: { fillColor: PRIMARY },
    head: [['Metric', 'Value']],
    body: [
      ['Average Mood Score', `${data.avgMoodScore.toFixed(2)} / 5`],
      ['Positive Days', `${data.positivePct}%`],
      ['Low Days', `${data.lowPct}%`],
      ['Mood Logs', `${data.totalMoodEntries}`],
      ['Active Days', `${data.uniqueActiveDays} / ${data.periodDays}`],
      ['Journal Entries', `${data.journalCount}`],
      ['MindMate Chats', `${data.mindMateUsage}`],
      ['Total Days Tracked', `${data.totalDaysUsed}`],
      ['Most Common Mood', data.mostCommonMood ?? '—'],
    ],
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  if (Object.keys(data.moodCounts).length) {
    y = sectionTitle(doc, 'Mood Distribution', y);
    autoTable(doc, {
      startY: y,
      theme: 'striped',
      headStyles: { fillColor: PRIMARY },
      head: [['Mood', 'Count', 'Share']],
      body: Object.entries(data.moodCounts)
        .sort(([, a], [, b]) => b - a)
        .map(([m, c]) => [m, String(c), `${Math.round((c / data.totalMoodEntries) * 100)}%`]),
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.recentMoods.length) {
    y = sectionTitle(doc, 'Recent Mood Entries', y);
    autoTable(doc, {
      startY: y,
      theme: 'grid',
      headStyles: { fillColor: PRIMARY },
      head: [['Date', 'Mood', 'Reason']],
      body: data.recentMoods.slice(0, 20).map(m => [m.date, m.mood, m.reason || '—']),
      columnStyles: { 2: { cellWidth: 100 } },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.recentJournals.length) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, 'Recent Journal Entries', y);
    autoTable(doc, {
      startY: y,
      theme: 'grid',
      headStyles: { fillColor: PRIMARY },
      head: [['Date', 'Preview']],
      body: data.recentJournals.slice(0, 15).map(j => [j.date, j.preview]),
      columnStyles: { 1: { cellWidth: 130 } },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.aiTip) {
    if (y > 250) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, 'AI Wellness Tip', y);
    doc.setFontSize(10);
    const split = doc.splitTextToSize(data.aiTip, 180);
    doc.text(split, 14, y);
  }

  footer(doc);
  doc.save(`wellness-report-${data.timeframe}-${new Date().toISOString().split('T')[0]}.pdf`);
}

export interface SleepReportData {
  userName: string;
  scheduledDuration: number | null;
  sleepTime?: string;
  wakeTime?: string;
  avgQualityScore: number;
  consistency: number;
  currentStreak: number;
  longestStreak: number;
  trackingRate: number;
  qualityLoggingRate: number;
  totalDays: number;
  qualityCounts: Record<string, number>;
  recentLogs: Array<{ date: string; confirmed: boolean; quality: string | null }>;
}

export function generateSleepReport(data: SleepReportData) {
  const doc = new jsPDF();
  header(doc, 'Sleep Report', `${data.userName} • ${new Date().toLocaleDateString()}`);

  let y = 38;
  y = sectionTitle(doc, 'Overview', y);
  autoTable(doc, {
    startY: y,
    theme: 'grid',
    headStyles: { fillColor: PRIMARY },
    head: [['Metric', 'Value']],
    body: [
      ['Sleep Time', data.sleepTime || '—'],
      ['Wake Time', data.wakeTime || '—'],
      ['Scheduled Duration', data.scheduledDuration ? `${data.scheduledDuration.toFixed(1)} h` : '—'],
      ['Average Quality', `${data.avgQualityScore.toFixed(2)} / 5`],
      ['Consistency', `${data.consistency}%`],
      ['Tracking Rate', `${data.trackingRate}%`],
      ['Quality Logging Rate', `${data.qualityLoggingRate}%`],
      ['Current Streak', `${data.currentStreak} days`],
      ['Longest Streak', `${data.longestStreak} days`],
      ['Days Logged', `${data.totalDays}`],
    ],
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  if (Object.keys(data.qualityCounts).length) {
    y = sectionTitle(doc, 'Quality Distribution', y);
    autoTable(doc, {
      startY: y,
      theme: 'striped',
      headStyles: { fillColor: PRIMARY },
      head: [['Quality', 'Nights']],
      body: Object.entries(data.qualityCounts)
        .sort(([, a], [, b]) => b - a)
        .map(([q, c]) => [q, String(c)]),
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.recentLogs.length) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, 'Recent Sleep Logs', y);
    autoTable(doc, {
      startY: y,
      theme: 'grid',
      headStyles: { fillColor: PRIMARY },
      head: [['Date', 'Confirmed', 'Quality']],
      body: data.recentLogs.slice(0, 30).map(l => [l.date, l.confirmed ? 'Yes' : 'No', l.quality || '—']),
    });
  }

  footer(doc);
  doc.save(`sleep-report-${new Date().toISOString().split('T')[0]}.pdf`);
}
