// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tipqgwdgplxlbwuvxyxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcHFnd2RncGx4bGJ3dXZ4eXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTg1MjYsImV4cCI6MjA2NzM3NDUyNn0.J9M4wG60dxyP17Jx95quletRqvJmUQbawEIwJS9MfO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});